### ISSUE TITLE
SetDelayed is not parsed correctly in the pattern scope

### ISSUE THREAD

**Issue by batracos** [ViktorQvarfordt/Sublime-WolframLanguage#17]
The regex for `Optional` is ``(?:\s*)(:)(?=[^:>])`` while it should be ``(?:\s*)(:)(?=[^:>=])``, given that `SetDelayed` (`:=`) has higher precedence in the WL tokeniser.

**Comment by chere005** [comment]
Is this fixed?

**Comment by batracos** [comment]
This was fixed in the last version.
