### ISSUE TITLE
What is `nb_code_styles` for?

### ISSUE THREAD

**Issue by shigma** [ViktorQvarfordt/Sublime-WolframLanguage#21]
See [here](https://github.com/ViktorQvarfordt/Sublime-WolframLanguage/blob/master/WolframLanguage.sublime-syntax#L50). `nb_code_styles` is assigned but never used. What is it for?

**Comment by batracos** [comment]
@chere005 did you add it? I don't remember writing it.

**Comment by Shigma** [comment]
Aha. I did add it but its reference has been removed.

It's meant for "notebook cell style", which may be displayed in an .nb file like this:
```mathematica
(* ::Input:: *)
1 + 2
```
Then the cell below will be displayed as an input cell.

This pattern sounds to have little significance. Maybe it's time to remove it.
