### ISSUE TITLE
Symbol highlighting

### ISSUE THREAD

**Issue by chere005** [ViktorQvarfordt/Sublime-WolframLanguage#3]
Hello,
Any symbol that shows up for completion should automatically be highlighted blue. Even without the brackets. This is especially to give highlighting to system defined Options.

**Comment by chere005** [comment]
This will also apply to Automatic, All etc, which is great.

**Comment by chere005** [comment]
Please release this so the changes are picked up on package control.

**Comment by ViktorQvarfordt** [comment]
Sorry, I had forgotten to updated the version tag. Thanks for reminding me!

**Comment by chere005** [comment]
No worries. Sorry I still haven't checked back on the other issues, it
remains on my todo list, but those don't seem to bother me as directly.

-S
