### ISSUE TITLE
For other editor

### ISSUE THREAD

**Issue by Alexey-T** [ViktorQvarfordt/Sublime-WolframLanguage#5]
Hi. As language is useful, maybe possible to make "lexer" for CudaText too?
http://wiki.freepascal.org/CudaText#Lexers_editing

**Comment by ViktorQvarfordt** [comment]
I don't use CudaText and have no intentions of developing packages for CudaText. If you want to do it, you can use this package as inspiration for how to parse the WolframLanguage, in particular the file [WolframLanguage.sublime-syntax](https://github.com/ViktorQvarfordt/Sublime-WolframLanguage/blob/master/WolframLanguage.sublime-syntax) is where the action happens.
