### ISSUE TITLE
Some problems about this repo

### ISSUE THREAD

**Issue by Shigma** [ViktorQvarfordt/Sublime-WolframLanguage#7]
I have find several problems about this repository.
1. Unused variable `long_op` was found. Also, some elements in the regex is rather confusing.
2. Variable `symb_op_unicode` will not be of any use, for Mathematica always transform them into more than two ascii letters or into forms like `\[this]`.
3. Named slot, such as `#name`, could not be rendered in the right way.
4. Not all built-symbols are functions. Symbols such as `Nothing` or `Automatic` or `LightBlue` should be treated like constant and thus should be removed from the function list.
5. Symbols like `.`, `_`, `:`, `` ` `` and `$` have quite different meanings in Wolfram Language compared with many other languages. However, these symbols are not treated properly.
6. No parenthesis matching.
7. Lack of snippets, which could be built with lines of Wolfram Language.

I'm willing to help solving these problems and optimize your repository. But this is a big project. In the early stage I can send pr to handle some minor problems, but I consider a collaborator will be of great use.

**Comment by ViktorQvarfordt** [comment]
Thanks for taking your time to raise these issues.

1. I created this syntax parser by porting my syntax parser for https://github.com/JuliaEditorSupport/Julia-sublime/ and it is possible that some parts are not used for wolfram. Some cleaning up would be nice.
2. True, but wolfram does accept pure unicode as inputs. I use unicode chars for variables frequently when coding math algorithms, with variables like alpha etc being nicer to read as α.
3. Good catch, that should be fixed.
4. Good catch, that should be fixed.
5. Good catch, that should be fixed.
6. Good catch, that should be fixed.
7. I think that adding snippets to this package is a good idea. What type of snippets do you have in mind? 

I'd be ok with making you a collaborator on this repo if you're up to it. I will not have that much time working on this right now.

**Comment by Shigma** [comment]
Concerning better completions and snippets, I have the following ideas. The first step is to generate a list of ``System` `` symbols and their usage (symbols beginning with `$` will be ignored at first, otherwise their completions might not work.
```
namespace = Select[Names["System`"~~WordCharacter..], PrintableASCIIQ];
Quiet[
    usageData = Table[
        namespace[[i]]->(Evaluate[Symbol[namespace[[i]]]]::usage),
    {i, Length@namespace}],
Message::name];
```
Some of the symbols are lack of document, so their usages are not defined:
```
withoutUsage = Quiet[Cases[usageData, (symbol_->_::usage):>symbol], Message::name];
withUsage = Quiet[Association[usageData][[Complement[Keys@usageData, withoutUsage]]], Message::name];
```
Some of the documented symbols are functions, with usage beginning with a fixed pattern (Box function themselves have their unique pattern):
```
functionA = Association@Select[Normal@withUsage, StringStartsQ[Values[#], "\!\(\*RowBox[{\""<>Keys[#]<>"\", \"[\""]&];
functionB = Association@Select[Normal@withUsage, StringStartsQ[Values[#], "\!\(\*RowBox[{"<>Keys[#]<>", \"[\""]&];
```
The Rest are non-function (we can assume these symbols are constant or built-in options or so on):
```
nonfunction = Complement[withUsage, functionA, functionB]//Keys;
```
With a clear category of different types of symbols, and their usages which will offer detailed information about the arguments of the functions, we can simply generate our completions and snippets in this way.

Hope my idea can be adapted to solve the problem.

Best Regards

**Comment by chere005** [comment]
@shigma we've started snippets in https://github.com/batracos/Sublime-WolframLanguage/pull/1

Are there any other issues from this list remaining?

**Comment by Shigma** [comment]
@chere005 
Thanks. The jobs you did helped a lot. Closed.
